### PR TITLE
edited non-standard methods using std

### PR DESCRIPTION
**Pull request by OxMarco**

### CODE REVIEW

**Comment by richkmeli** [comment]
I saw you used the STD thread, that library is available since C++11 [(std::thread),](http://en.cppreference.com/w/cpp/thread/thread) so i suppose you had edited the Makefile, adding the C++11 flag, before you compiled the source code, hadn't you?
At the moment, this project is developed with C++98 standard. 

The types and methods i used, are in Windows library, and it's in accordance with the aim of this project, that is to create a framework for Windows; moreover some methods in Windows.h needs of some particular type (obviously in Windows.h) to work properly, so it means, if you change one of these with the equivalent in the STD library you need to test a lot of things.

**Comment by richkmeli** [comment]
I saw you used the STD thread, that library is available since C++11 [(std::thread),](http://en.cppreference.com/w/cpp/thread/thread) so I suppose you had edited the Makefile, adding the C++11 flag, before you compiled the source code, hadn't you?
At the moment, this project is developed with C++98 standard. 

The types and methods I used, are in Windows library, and it's in accordance with the aim of this project, that is to create a framework for Windows; moreover some methods in Windows.h needs of some particular type (obviously in Windows.h) to work properly, so it means, if you change one of these with the equivalent in the STD library you need to test a lot of things.

**Comment by richkmeli** [comment]
I saw you used the STD thread, that library is available since C++11 [(std::thread),](http://en.cppreference.com/w/cpp/thread/thread) so I suppose you had edited the Makefile, adding the C++11 flag, before you compiled the source code, hadn't you?
At the moment, this project is developed with C++98 standard. 

The types and methods I used, are in Windows library, and it's in accordance with the aim of this project, that is to create a framework for Windows; moreover some methods in Windows.h need some particular type (obviously in Windows.h) to work properly, so it means, if you change one of these with the equivalent in the STD library you need to test a lot of things.

**Comment by OxMarco** [comment]
Let's continue on Telegram. Pull request is closed for now

**Pull request closed without merging**
